apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: {{.Values.SCALE}}
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: {{.Values.POSTGRES_IMAGE}}
          name: postgres
          env:
          - name: POSTGRES_PASSWORD
            value: {{.Values.POSTGRES_PASSWORD}}
          - name: POSTGRES_USER
            value: {{.Values.POSTGRES_USER}}
          - name: POSTGRES_DB
            value: {{.Values.POSTGRES_DB}}
          ports:
            - containerPort: {{.Values.POSTGRES_CONTAINER_PORT}}
              name: postgres
          volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgresql
      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-volumeclaim