apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-app
  name: postgres-app
spec:
  type: ClusterIP
  ports:
    - port: {{.Values.POSTGRES_CONTAINER_PORT}}
  selector:
    app: postgres