apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
  labels:
    app: python
spec:
  replicas: {{.Values.SCALE}}
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
        - image: {{.Values.PYTHON_IMAGE}}
          imagePullPollicy: Always
          name: python
          ports:
            - containerPort: {{.Values.PYTHON_CONTAINER_PORT}}
              name: python