apiVersion: v1
kind: Service
metadata:
  labels:
    app: python-app
  name: python-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: {{.Values.PYTHON_CONTAINER_PORT}}
      protocol: TCP
  selector:
    app: python